# Generated by Django 5.2.14 on 2026-06-26 05:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asset_code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=180)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("LAPTOP", "Laptop"),
                            ("DESKTOP", "Desktop"),
                            ("MOBILE", "Mobile"),
                            ("TABLET", "Tablet"),
                            ("SIM", "SIM Card"),
                            ("ACCESSORY", "Accessory"),
                            ("SOFTWARE", "Software License"),
                            ("NETWORK", "Network Device"),
                            ("OTHER", "Other"),
                        ],
                        default="LAPTOP",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("ASSIGNED", "Assigned"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("DAMAGED", "Damaged"),
                            ("LOST", "Lost"),
                            ("RETIRED", "Retired"),
                        ],
                        default="AVAILABLE",
                        max_length=30,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=120)),
                ("model", models.CharField(blank=True, max_length=120)),
                ("serial_number", models.CharField(blank=True, max_length=120)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("warranty_end_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("vendor", models.CharField(blank=True, max_length=180)),
                ("location", models.CharField(blank=True, max_length=180)),
                ("notes", models.TextField(blank=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["asset_code"],
            },
        ),
        migrations.CreateModel(
            name="AssetAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ASSIGNED", "Assigned"), ("RETURNED", "Returned")],
                        default="ASSIGNED",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expected_return_date", models.DateField(blank=True, null=True)),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                ("condition_at_issue", models.TextField(blank=True)),
                ("condition_at_return", models.TextField(blank=True)),
                ("issue_notes", models.TextField(blank=True)),
                ("return_notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssetDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("INVOICE", "Invoice"),
                            ("WARRANTY", "Warranty"),
                            ("HANDOVER", "Handover"),
                            ("PHOTO", "Photo"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size", models.PositiveIntegerField(default=0)),
                ("data", models.BinaryField()),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("maintenance_type", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=30,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("vendor", models.CharField(blank=True, max_length=180)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
