# Generated by Django 5.2.14 on 2026-06-26 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("assets", "0001_initial"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_assets",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="assetassignment",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="assetassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asset_assignments_done",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assetassignment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_assignments",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="assetassignment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
            ),
        ),
        migrations.AddField(
            model_name="assetassignment",
            name="returned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asset_returns_done",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assetcategory",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="assets.assetcategory",
            ),
        ),
        migrations.AddField(
            model_name="assetdocument",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="assetdocument",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
            ),
        ),
        migrations.AddField(
            model_name="assetdocument",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_asset_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assetmaintenance",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_records",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="assetmaintenance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_asset_maintenance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assetmaintenance",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
            ),
        ),
        migrations.AddIndex(
            model_name="assetassignment",
            index=models.Index(
                fields=["organization", "status"], name="assets_asse_organiz_36e7d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetassignment",
            index=models.Index(
                fields=["organization", "employee"],
                name="assets_asse_organiz_a81990_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetassignment",
            index=models.Index(
                fields=["organization", "asset"], name="assets_asse_organiz_6e67de_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assetcategory",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["organization", "status"], name="assets_asse_organiz_ad90f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["organization", "asset_type"],
                name="assets_asse_organiz_2c4606_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["organization", "assigned_to"],
                name="assets_asse_organiz_0db23b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="asset",
            unique_together={("organization", "asset_code")},
        ),
        migrations.AddIndex(
            model_name="assetdocument",
            index=models.Index(
                fields=["organization", "asset"], name="assets_asse_organiz_cbc949_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetmaintenance",
            index=models.Index(
                fields=["organization", "status"], name="assets_asse_organiz_7647e6_idx"
            ),
        ),
    ]
