# Generated by Django 5.2.14 on 2026-06-26 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee_code", models.CharField(max_length=50)),
                ("designation", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("personal_email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("permanent_address", models.TextField(blank=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=30)),
                ("blood_group", models.CharField(blank=True, max_length=10)),
                ("marital_status", models.CharField(blank=True, max_length=30)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "emergency_contact_relation",
                    models.CharField(blank=True, max_length=80),
                ),
                ("bank_name", models.CharField(blank=True, max_length=120)),
                ("bank_account_number", models.CharField(blank=True, max_length=80)),
                ("bank_ifsc", models.CharField(blank=True, max_length=30)),
                ("bank_branch", models.CharField(blank=True, max_length=120)),
                ("tax_id", models.CharField(blank=True, max_length=80)),
                ("date_of_joining", models.DateField(blank=True, null=True)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("PART_TIME", "Part Time"),
                            ("CONTRACT", "Contract"),
                            ("INTERN", "Intern"),
                        ],
                        default="FULL_TIME",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PROBATION", "Probation"),
                            ("NOTICE", "Notice"),
                            ("EXITED", "Exited"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "salary_basic",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="hr.department",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_members",
                        to="hr.employee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "employee_code")},
            },
        ),
    ]
