# Generated by Django 5.2.14 on 2026-06-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("check_in", models.DateTimeField(blank=True, null=True)),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("HALF_DAY", "Half Day"),
                            ("LATE", "Late"),
                            ("ON_LEAVE", "On Leave"),
                            ("HOLIDAY", "Holiday"),
                            ("WEEK_OFF", "Weekly Off"),
                        ],
                        default="PRESENT",
                        max_length=20,
                    ),
                ),
                (
                    "work_mode",
                    models.CharField(
                        choices=[
                            ("OFFICE", "Office"),
                            ("REMOTE", "Remote"),
                            ("HYBRID", "Hybrid"),
                            ("FIELD", "Field"),
                        ],
                        default="OFFICE",
                        max_length=20,
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                ("late_minutes", models.PositiveIntegerField(default=0)),
                ("overtime_minutes", models.PositiveIntegerField(default=0)),
                ("is_holiday", models.BooleanField(default=False)),
                ("is_weekly_off", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeShiftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("date", models.DateField()),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public Holiday"),
                            ("COMPANY", "Company Holiday"),
                            ("FESTIVAL", "Festival"),
                            ("OPTIONAL", "Optional Holiday"),
                        ],
                        default="PUBLIC",
                        max_length=20,
                    ),
                ),
                ("is_optional", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("break_minutes", models.PositiveIntegerField(default=60)),
                ("grace_minutes", models.PositiveIntegerField(default=10)),
                (
                    "half_day_hours",
                    models.DecimalField(decimal_places=2, default=4, max_digits=4),
                ),
                (
                    "full_day_hours",
                    models.DecimalField(decimal_places=2, default=8, max_digits=4),
                ),
                ("overtime_after_minutes", models.PositiveIntegerField(default=30)),
                (
                    "weekly_off_days",
                    models.CharField(
                        default="SUN",
                        help_text="Comma-separated day codes like SUN or SAT,SUN",
                        max_length=40,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
