# Generated by Django 5.2.14 on 2026-06-26 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("attendance", "0001_initial"),
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
            ),
        ),
        migrations.AddField(
            model_name="employeeshiftassignment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_assignments",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeeshiftassignment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
            ),
        ),
        migrations.AddField(
            model_name="holiday",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="holiday",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="attendance.holiday",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
            ),
        ),
        migrations.AddField(
            model_name="employeeshiftassignment",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_assignments",
                to="attendance.shift",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="attendance.shift",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="holiday",
            unique_together={("organization", "date", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together={("organization", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("organization", "employee", "date")},
        ),
    ]
