# Generated by Django 5.2.14 on 2026-06-26 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OffboardingCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exit_type",
                    models.CharField(
                        choices=[
                            ("RESIGNATION", "Resignation"),
                            ("TERMINATION", "Termination"),
                            ("END_OF_CONTRACT", "End of Contract"),
                            ("RETIREMENT", "Retirement"),
                            ("OTHER", "Other"),
                        ],
                        default="RESIGNATION",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("HR_REVIEW", "HR Review"),
                            ("CLEARANCE_IN_PROGRESS", "Clearance In Progress"),
                            ("FINAL_SETTLEMENT", "Final Settlement"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=40,
                    ),
                ),
                ("resignation_date", models.DateField(blank=True, null=True)),
                ("requested_last_working_day", models.DateField(blank=True, null=True)),
                ("approved_last_working_day", models.DateField(blank=True, null=True)),
                ("notice_period_days", models.PositiveIntegerField(default=0)),
                ("reason", models.TextField(blank=True)),
                ("employee_notes", models.TextField(blank=True)),
                ("manager_notes", models.TextField(blank=True)),
                ("hr_notes", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("login_deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_offboarding_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_offboarding_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_offboarding_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offboarding_cases",
                        to="hr.employee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinalSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "salary_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "basic_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "leave_encashment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "expense_reimbursement",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "notice_recovery",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "asset_recovery",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_payable",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("payment_reference", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_final_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_final_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepared_final_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_settlement",
                        to="offboarding.offboardingcase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OffboardingClearanceTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("HR", "HR"),
                            ("IT", "IT"),
                            ("FINANCE", "Finance"),
                            ("MANAGER", "Manager"),
                            ("ADMIN", "Admin"),
                            ("OTHER", "Other"),
                        ],
                        default="HR",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CLEARED", "Cleared"),
                            ("REJECTED", "Rejected"),
                            ("WAIVED", "Waived"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_offboarding_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clearance_tasks",
                        to="offboarding.offboardingcase",
                    ),
                ),
                (
                    "cleared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cleared_offboarding_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "due_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="OffboardingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("RESIGNATION", "Resignation"),
                            ("RELIEVING", "Relieving Letter"),
                            ("EXPERIENCE", "Experience Letter"),
                            ("SETTLEMENT", "Settlement"),
                            ("CLEARANCE", "Clearance"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size", models.PositiveIntegerField(default=0)),
                ("data", models.BinaryField()),
                ("notes", models.TextField(blank=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="offboarding.offboardingcase",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_offboarding_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="offboardingcase",
            index=models.Index(
                fields=["organization", "status"], name="offboarding_organiz_a36c95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offboardingcase",
            index=models.Index(
                fields=["organization", "employee"],
                name="offboarding_organiz_96a6ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="offboardingcase",
            index=models.Index(
                fields=["organization", "approved_last_working_day"],
                name="offboarding_organiz_11bb11_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="finalsettlement",
            index=models.Index(
                fields=["organization", "status"], name="offboarding_organiz_e5367b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offboardingclearancetask",
            index=models.Index(
                fields=["organization", "status"], name="offboarding_organiz_bf7911_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offboardingclearancetask",
            index=models.Index(
                fields=["organization", "case"], name="offboarding_organiz_85bc06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offboardingdocument",
            index=models.Index(
                fields=["organization", "case"], name="offboarding_organiz_1e043d_idx"
            ),
        ),
    ]
