# Generated by Django 5.2.14 on 2026-06-26 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LetterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=180)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("OFFER", "Offer Letter"),
                            ("APPOINTMENT", "Appointment Letter"),
                            ("CONFIRMATION", "Confirmation Letter"),
                            ("INCREMENT", "Increment Letter"),
                            ("SALARY", "Salary Certificate"),
                            ("EXPERIENCE", "Experience Letter"),
                            ("RELIEVING", "Relieving Letter"),
                            ("WARNING", "Warning Letter"),
                            ("NOC", "NOC"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=30)),
                ("description", models.TextField(blank=True)),
                (
                    "content",
                    models.TextField(
                        help_text="Use Django-style variables like {{ employee.employee_code }} or {{ custom.amount }}."
                    ),
                ),
                ("available_variables", models.JSONField(blank=True, default=list)),
                ("requires_approval", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_letter_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("letter_number", models.CharField(blank=True, max_length=80)),
                ("title", models.CharField(max_length=220)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("OFFER", "Offer Letter"),
                            ("APPOINTMENT", "Appointment Letter"),
                            ("CONFIRMATION", "Confirmation Letter"),
                            ("INCREMENT", "Increment Letter"),
                            ("SALARY", "Salary Certificate"),
                            ("EXPERIENCE", "Experience Letter"),
                            ("RELIEVING", "Relieving Letter"),
                            ("WARNING", "Warning Letter"),
                            ("NOC", "NOC"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("custom_variables", models.JSONField(blank=True, default=dict)),
                ("rendered_content", models.TextField(blank=True)),
                ("document_data", models.BinaryField(blank=True, null=True)),
                ("document_filename", models.CharField(blank=True, max_length=255)),
                ("document_content_type", models.CharField(blank=True, max_length=120)),
                ("document_size", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("GENERATED", "Generated"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SIGNED", "Signed"),
                            ("ISSUED", "Issued"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_letters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_letters",
                        to="hr.employee",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_letters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_letters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_letters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_letters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_letters",
                        to="hrletters.lettertemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LetterAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=80)),
                ("note", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="letter_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="hrletters.generatedletter",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "letter", "action"],
                        name="hrletters_l_organiz_04de8b_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="lettertemplate",
            index=models.Index(
                fields=["organization", "category"],
                name="hrletters_l_organiz_a99208_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lettertemplate",
            index=models.Index(
                fields=["organization", "is_active"],
                name="hrletters_l_organiz_3355ff_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lettertemplate",
            unique_together={("organization", "code", "version")},
        ),
        migrations.AddIndex(
            model_name="generatedletter",
            index=models.Index(
                fields=["organization", "employee", "status"],
                name="hrletters_g_organiz_b10be2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generatedletter",
            index=models.Index(
                fields=["organization", "category"],
                name="hrletters_g_organiz_8646c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generatedletter",
            index=models.Index(
                fields=["organization", "status"], name="hrletters_g_organiz_7c11a2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="generatedletter",
            unique_together={("organization", "letter_number")},
        ),
    ]
