# Generated by Django 5.2.14 on 2026-06-26 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("expenses", "0001_initial"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expenseclaim",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_claims",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="expenseclaim",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
            ),
        ),
        migrations.AddField(
            model_name="expenseclaim",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paid_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expenseclaim",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="expensecategory",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="expenseclaim",
            index=models.Index(
                fields=["organization", "status"], name="expenses_ex_organiz_5bd929_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expenseclaim",
            index=models.Index(
                fields=["organization", "expense_date"],
                name="expenses_ex_organiz_625a36_idx",
            ),
        ),
    ]
