from datetime import date
from django.template import Context, Template
from django.utils.html import escape


DEFAULT_VARIABLES = [
    'organization.name',
    'today',
    'employee.employee_code',
    'employee.first_name',
    'employee.last_name',
    'employee.full_name',
    'employee.email',
    'employee.department',
    'employee.designation',
    'employee.date_of_joining',
    'employee.salary_basic',
    'employee.manager_name',
    'custom.amount',
    'custom.effective_date',
    'custom.reason',
    'custom.signatory_name',
    'custom.signatory_designation',
]


def employee_context(employee):
    user = employee.user
    manager_name = ''
    if employee.manager and employee.manager.user:
        manager_user = employee.manager.user
        manager_name = f'{manager_user.first_name} {manager_user.last_name}'.strip() or manager_user.email
    return {
        'employee_code': employee.employee_code,
        'first_name': user.first_name,
        'last_name': user.last_name,
        'full_name': f'{user.first_name} {user.last_name}'.strip() or user.email,
        'email': user.email,
        'phone': employee.phone,
        'department': employee.department.name if employee.department else '',
        'designation': employee.designation,
        'date_of_joining': employee.date_of_joining,
        'employment_type': employee.employment_type,
        'salary_basic': employee.salary_basic,
        'manager_name': manager_name,
        'bank_name': employee.bank_name,
        'tax_id': employee.tax_id,
    }


def render_letter(template, employee, custom_variables=None):
    custom_variables = custom_variables or {}
    context = Context({
        'organization': {
            'name': employee.organization.name,
            'slug': employee.organization.slug,
            'industry': employee.organization.industry,
        },
        'employee': employee_context(employee),
        'custom': custom_variables,
        'today': date.today(),
    }, autoescape=True)
    body = Template(template.content).render(context)
    title = escape(template.name)
    return f'''<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>{title}</title>
  <style>
    body {{ font-family: Arial, sans-serif; color: #111827; line-height: 1.6; padding: 40px; }}
    .letter {{ max-width: 850px; margin: 0 auto; }}
    .meta {{ color: #6b7280; font-size: 13px; margin-bottom: 24px; }}
  </style>
</head>
<body>
  <div class="letter">
    <div class="meta">Generated by {escape(employee.organization.name)} on {date.today()}</div>
    {body}
  </div>
</body>
</html>'''
