# Generated by Django 5.2.14 on 2026-06-26 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                (
                    "component_type",
                    models.CharField(
                        choices=[("EARNING", "Earning"), ("DEDUCTION", "Deduction")],
                        max_length=20,
                    ),
                ),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed Amount"),
                            ("PERCENT_BASIC", "Percent of Basic"),
                            ("PERCENT_GROSS", "Percent of Gross"),
                        ],
                        default="FIXED",
                        max_length=30,
                    ),
                ),
                (
                    "default_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "default_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("is_taxable", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["component_type", "name"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.PositiveIntegerField()),
                ("year", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("GENERATED", "Generated"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
                "unique_together": {("organization", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.PositiveIntegerField()),
                ("year", models.PositiveIntegerField()),
                (
                    "basic",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gross_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "expected_work_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "present_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "paid_leave_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "unpaid_leave_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "absent_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "half_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "payable_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "loss_of_pay_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("worked_minutes", models.PositiveIntegerField(default=0)),
                ("overtime_minutes", models.PositiveIntegerField(default=0)),
                (
                    "overtime_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "lop_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="hr.employee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="payroll.payrollrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "employee__employee_code"],
                "unique_together": {("organization", "employee", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="PayslipLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                (
                    "line_type",
                    models.CharField(
                        choices=[("EARNING", "Earning"), ("DEDUCTION", "Deduction")],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payroll.payrollcomponent",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "payslip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="payroll.payslip",
                    ),
                ),
            ],
            options={
                "ordering": ["line_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSalaryComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_components",
                        to="hr.employee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_components",
                        to="payroll.payrollcomponent",
                    ),
                ),
            ],
            options={
                "ordering": ["employee__employee_code", "component__name"],
                "unique_together": {
                    ("organization", "employee", "component", "effective_from")
                },
            },
        ),
        migrations.CreateModel(
            name="PayrollRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.PositiveIntegerField()),
                ("year", models.PositiveIntegerField()),
                (
                    "basic",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                            ("HOLD", "Hold"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_records",
                        to="hr.employee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
                "unique_together": {("organization", "employee", "month", "year")},
            },
        ),
    ]
