# Generated by Django 5.2.14 on 2026-06-26 05:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=180)),
                ("category", models.CharField(blank=True, max_length=120)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                            ("COMPLIANCE", "Compliance"),
                        ],
                        default="BEGINNER",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("skills_covered", models.TextField(blank=True)),
                (
                    "duration_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("is_mandatory", models.BooleanField(default=False)),
                ("audience_roles", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_training_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("instructions", models.TextField(blank=True)),
                (
                    "max_score",
                    models.DecimalField(decimal_places=2, default=100, max_digits=8),
                ),
                (
                    "passing_score",
                    models.DecimalField(decimal_places=2, default=60, max_digits=8),
                ),
                ("questions", models.JSONField(blank=True, default=list)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_training_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="training.trainingcourse",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ASSIGNED",
                        max_length=20,
                    ),
                ),
                ("progress_percent", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_training_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="training.trainingcourse",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_enrollments",
                        to="hr.employee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("certificate_number", models.CharField(max_length=120)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_certificates",
                        to="hr.employee",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_training_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="training.trainingcourse",
                    ),
                ),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="training.trainingenrollment",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("DOCUMENT", "Document"),
                            ("VIDEO", "Video"),
                            ("LINK", "Link"),
                            ("SLIDE", "Slide"),
                            ("OTHER", "Other"),
                        ],
                        default="DOCUMENT",
                        max_length=20,
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("file_data", models.BinaryField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="training.trainingcourse",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_training_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["course", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("answers", models.JSONField(blank=True, default=dict)),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("REVIEWED", "Reviewed"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="training.trainingassessment",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_submissions",
                        to="hr.employee",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="training.trainingenrollment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_training_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="trainingcourse",
            index=models.Index(
                fields=["organization", "status"], name="training_tr_organiz_c7f233_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingcourse",
            index=models.Index(
                fields=["organization", "category"],
                name="training_tr_organiz_122685_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trainingcourse",
            unique_together={("organization", "code")},
        ),
        migrations.AddIndex(
            model_name="trainingassessment",
            index=models.Index(
                fields=["organization", "course", "is_published"],
                name="training_tr_organiz_096d3c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingenrollment",
            index=models.Index(
                fields=["organization", "status"], name="training_tr_organiz_7000d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingenrollment",
            index=models.Index(
                fields=["organization", "employee"],
                name="training_tr_organiz_6c5389_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingenrollment",
            index=models.Index(
                fields=["organization", "course"], name="training_tr_organiz_60eb1b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trainingenrollment",
            unique_together={("organization", "course", "employee")},
        ),
        migrations.AddIndex(
            model_name="trainingcertificate",
            index=models.Index(
                fields=["organization", "employee"],
                name="training_tr_organiz_cc3f05_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trainingcertificate",
            unique_together={("organization", "certificate_number")},
        ),
        migrations.AddIndex(
            model_name="trainingmaterial",
            index=models.Index(
                fields=["organization", "course"], name="training_tr_organiz_339ca4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingsubmission",
            index=models.Index(
                fields=["organization", "assessment"],
                name="training_tr_organiz_e54089_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingsubmission",
            index=models.Index(
                fields=["organization", "employee"],
                name="training_tr_organiz_2941d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingsubmission",
            index=models.Index(
                fields=["organization", "status"], name="training_tr_organiz_c890bc_idx"
            ),
        ),
    ]
