# Generated by Django 5.2.14 on 2026-06-26 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("code", models.CharField(max_length=60)),
                ("version", models.CharField(default="1.0", max_length=30)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HR", "HR"),
                            ("ATTENDANCE", "Attendance"),
                            ("LEAVE", "Leave"),
                            ("PAYROLL", "Payroll"),
                            ("EXPENSE", "Expense"),
                            ("IT", "IT"),
                            ("SECURITY", "Security"),
                            ("CONDUCT", "Code of Conduct"),
                            ("OTHER", "Other"),
                        ],
                        default="HR",
                        max_length=30,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("content", models.TextField(blank=True)),
                ("audience_roles", models.JSONField(blank=True, default=list)),
                ("requires_acknowledgement", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("document_file_name", models.CharField(blank=True, max_length=255)),
                ("document_content_type", models.CharField(blank=True, max_length=120)),
                ("document_size", models.PositiveIntegerField(default=0)),
                ("document_data", models.BinaryField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyAcknowledgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgements",
                        to="policies.companypolicy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_acknowledgements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-acknowledged_at"],
            },
        ),
        migrations.AddIndex(
            model_name="companypolicy",
            index=models.Index(
                fields=["organization", "category"],
                name="policies_co_organiz_68e952_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="companypolicy",
            index=models.Index(
                fields=["organization", "is_published"],
                name="policies_co_organiz_f2cf27_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="companypolicy",
            index=models.Index(
                fields=["organization", "code", "version"],
                name="policies_co_organiz_b598ae_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="companypolicy",
            unique_together={("organization", "code", "version")},
        ),
        migrations.AddIndex(
            model_name="policyacknowledgement",
            index=models.Index(
                fields=["organization", "user"], name="policies_po_organiz_585ed4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policyacknowledgement",
            index=models.Index(
                fields=["organization", "policy"], name="policies_po_organiz_c20f79_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="policyacknowledgement",
            unique_together={("policy", "user")},
        ),
    ]
