# Generated by Django 5.2.14 on 2026-06-26 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("JOB_PORTAL", "Job Portal"),
                            ("LINKEDIN", "LinkedIn"),
                            ("REFERRAL", "Referral"),
                            ("AGENCY", "Agency"),
                            ("WALK_IN", "Walk-in"),
                            ("CAREERS_PAGE", "Careers Page"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("current_company", models.CharField(blank=True, max_length=180)),
                ("current_designation", models.CharField(blank=True, max_length=180)),
                (
                    "experience_years",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "current_ctc",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "expected_ctc",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notice_period_days", models.PositiveIntegerField(default=0)),
                ("skills", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("SCREENING", "Screening"),
                            ("SHORTLISTED", "Shortlisted"),
                            ("INTERVIEW", "Interview"),
                            ("OFFERED", "Offered"),
                            ("HIRED", "Hired"),
                            ("REJECTED", "Rejected"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("resume_file_name", models.CharField(blank=True, max_length=255)),
                ("resume_content_type", models.CharField(blank=True, max_length=120)),
                ("resume_size", models.PositiveIntegerField(default=0)),
                ("resume_data", models.BinaryField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job_code", models.CharField(max_length=60)),
                ("title", models.CharField(max_length=180)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("PART_TIME", "Part Time"),
                            ("CONTRACT", "Contract"),
                            ("INTERN", "Intern"),
                        ],
                        default="FULL_TIME",
                        max_length=20,
                    ),
                ),
                (
                    "work_mode",
                    models.CharField(
                        choices=[
                            ("OFFICE", "Office"),
                            ("REMOTE", "Remote"),
                            ("HYBRID", "Hybrid"),
                            ("FIELD", "Field"),
                        ],
                        default="OFFICE",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=180)),
                ("openings_count", models.PositiveIntegerField(default=1)),
                (
                    "min_experience",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "max_experience",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "salary_min",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "salary_max",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("description", models.TextField(blank=True)),
                ("requirements", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("ON_HOLD", "On Hold"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("target_start_date", models.DateField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_job_openings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_openings",
                        to="hr.department",
                    ),
                ),
                (
                    "hiring_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_job_openings",
                        to="hr.employee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "round_type",
                    models.CharField(
                        choices=[
                            ("HR", "HR"),
                            ("TECHNICAL", "Technical"),
                            ("MANAGERIAL", "Managerial"),
                            ("FINAL", "Final"),
                        ],
                        default="HR",
                        max_length=30,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("PHONE", "Phone"),
                        ],
                        default="ONLINE",
                        max_length=20,
                    ),
                ),
                ("meeting_link", models.URLField(blank=True)),
                ("location", models.CharField(blank=True, max_length=180)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SELECTED", "Selected"),
                            ("REJECTED", "Rejected"),
                            ("HOLD", "Hold"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                ("feedback", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="recruitment.candidate",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_interviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_interviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interview_rounds",
                        to="hr.employee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "job_opening",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interviews",
                        to="recruitment.jobopening",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_at", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="candidate",
            name="job_opening",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="recruitment.jobopening",
            ),
        ),
        migrations.CreateModel(
            name="OfferLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("offer_number", models.CharField(max_length=80)),
                ("offered_designation", models.CharField(max_length=180)),
                ("joining_date", models.DateField(blank=True, null=True)),
                (
                    "salary_basic",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "ctc",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("CONVERTED", "Converted"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("document_file_name", models.CharField(blank=True, max_length=255)),
                ("document_content_type", models.CharField(blank=True, max_length=120)),
                ("document_size", models.PositiveIntegerField(default=0)),
                ("document_data", models.BinaryField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="recruitment.candidate",
                    ),
                ),
                (
                    "converted_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_offer_letters",
                        to="hr.employee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_offer_letters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offer_letters",
                        to="hr.department",
                    ),
                ),
                (
                    "job_opening",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offers",
                        to="recruitment.jobopening",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="jobopening",
            index=models.Index(
                fields=["organization", "status"], name="recruitment_organiz_0f548d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobopening",
            index=models.Index(
                fields=["organization", "department"],
                name="recruitment_organiz_7b40c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobopening",
            index=models.Index(
                fields=["organization", "hiring_manager"],
                name="recruitment_organiz_7d35c4_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobopening",
            unique_together={("organization", "job_code")},
        ),
        migrations.AddIndex(
            model_name="interviewround",
            index=models.Index(
                fields=["organization", "candidate"],
                name="recruitment_organiz_ffec2f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interviewround",
            index=models.Index(
                fields=["organization", "status"], name="recruitment_organiz_06781c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewround",
            index=models.Index(
                fields=["organization", "interviewer"],
                name="recruitment_organiz_027e1c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["organization", "status"], name="recruitment_organiz_20a0da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["organization", "job_opening"],
                name="recruitment_organiz_171ee6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["organization", "email"], name="recruitment_organiz_53bd03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offerletter",
            index=models.Index(
                fields=["organization", "status"], name="recruitment_organiz_a89144_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offerletter",
            index=models.Index(
                fields=["organization", "candidate"],
                name="recruitment_organiz_52a260_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="offerletter",
            index=models.Index(
                fields=["organization", "job_opening"],
                name="recruitment_organiz_f20ad6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="offerletter",
            unique_together={("organization", "offer_number")},
        ),
    ]
