# Generated by Django 5.2.14 on 2026-06-26 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("FULL_DB", "Full Database"),
                            ("SCHEMA_ONLY", "Schema Only"),
                            ("DATA_ONLY", "Data Only"),
                            ("MANUAL_EXPORT", "Manual Export"),
                        ],
                        default="FULL_DB",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("command_used", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backup_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("app_name", models.CharField(default="EmployeeHub", max_length=120)),
                ("country", models.CharField(default="India", max_length=80)),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=80)),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("DD-MM-YYYY", "DD-MM-YYYY"),
                            ("MM-DD-YYYY", "MM-DD-YYYY"),
                            ("YYYY-MM-DD", "YYYY-MM-DD"),
                        ],
                        default="DD-MM-YYYY",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "fiscal_year_start_month",
                    models.PositiveSmallIntegerField(default=4),
                ),
                ("leave_year_start_month", models.PositiveSmallIntegerField(default=1)),
                (
                    "standard_working_hours_per_day",
                    models.DecimalField(decimal_places=2, default=8, max_digits=4),
                ),
                ("attendance_grace_minutes", models.PositiveIntegerField(default=10)),
                (
                    "half_day_threshold_hours",
                    models.DecimalField(decimal_places=2, default=4, max_digits=4),
                ),
                (
                    "overtime_rate_per_hour",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("weekly_off_days", models.JSONField(blank=True, default=list)),
                ("default_notice_period_days", models.PositiveIntegerField(default=30)),
                ("default_probation_days", models.PositiveIntegerField(default=90)),
                ("payroll_lock_day", models.PositiveSmallIntegerField(default=7)),
                ("document_max_upload_mb", models.PositiveIntegerField(default=10)),
                ("data_retention_days", models.PositiveIntegerField(default=2555)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("allow_employee_profile_edit", models.BooleanField(default=True)),
                ("allow_employee_self_attendance", models.BooleanField(default=True)),
                (
                    "allow_employee_expense_submission",
                    models.BooleanField(default=True),
                ),
                ("allow_employee_self_enrollment", models.BooleanField(default=True)),
                ("enable_ip_restriction", models.BooleanField(default=False)),
                ("allowed_ip_ranges", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization",)},
            },
        ),
    ]
