# Generated by Django 5.2.14 on 2026-06-26 05:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "To Do"),
                            ("IN_PROGRESS", "In Progress"),
                            ("REVIEW", "Review"),
                            ("DONE", "Done"),
                            ("BLOCKED", "Blocked"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="TODO",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_project_tasks",
                        to="hr.employee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project_code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=180)),
                ("client_name", models.CharField(blank=True, max_length=180)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("ACTIVE", "Active"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("is_billable", models.BooleanField(default=True)),
                (
                    "budget_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "project_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_work_projects",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TimesheetEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "work_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "approved_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("is_billable", models.BooleanField(default=True)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_entries",
                        to="hr.employee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_timesheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timesheet_entries",
                        to="timesheets.projecttask",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_entries",
                        to="timesheets.workproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-work_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="projecttask",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="timesheets.workproject",
            ),
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project_role",
                    models.CharField(
                        choices=[
                            ("MEMBER", "Member"),
                            ("LEAD", "Lead"),
                            ("MANAGER", "Manager"),
                            ("QA", "QA"),
                        ],
                        default="MEMBER",
                        max_length=20,
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_at",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("released_at", models.DateField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to="hr.employee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="timesheets.workproject",
                    ),
                ),
            ],
            options={
                "ordering": ["project__name", "employee__employee_code"],
            },
        ),
        migrations.AddIndex(
            model_name="workproject",
            index=models.Index(
                fields=["organization", "status"], name="timesheets__organiz_5b6e32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workproject",
            index=models.Index(
                fields=["organization", "project_manager"],
                name="timesheets__organiz_0f3602_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workproject",
            unique_together={("organization", "project_code")},
        ),
        migrations.AddIndex(
            model_name="timesheetentry",
            index=models.Index(
                fields=["organization", "employee", "work_date"],
                name="timesheets__organiz_8ab7f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timesheetentry",
            index=models.Index(
                fields=["organization", "project", "work_date"],
                name="timesheets__organiz_9eeccc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timesheetentry",
            index=models.Index(
                fields=["organization", "status"], name="timesheets__organiz_563558_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projecttask",
            index=models.Index(
                fields=["organization", "project", "status"],
                name="timesheets__organiz_d4daee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projecttask",
            index=models.Index(
                fields=["organization", "assigned_to", "status"],
                name="timesheets__organiz_3cf2a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(
                fields=["organization", "project", "is_active"],
                name="timesheets__organiz_9de874_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(
                fields=["organization", "employee", "is_active"],
                name="timesheets__organiz_032563_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectmembership",
            unique_together={("organization", "project", "employee")},
        ),
    ]
