# Generated by Django 5.2.14 on 2026-06-26 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("helpdesk", "0001_initial"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support_tickets",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="ticketattachment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
            ),
        ),
        migrations.AddField(
            model_name="ticketattachment",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="helpdesk.supportticket",
            ),
        ),
        migrations.AddField(
            model_name="ticketattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="helpdesk_attachments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticketcategory",
            name="default_assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_helpdesk_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticketcategory",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="helpdesk.ticketcategory",
            ),
        ),
        migrations.AddField(
            model_name="ticketcomment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="helpdesk_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticketcomment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
            ),
        ),
        migrations.AddField(
            model_name="ticketcomment",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="helpdesk.supportticket",
            ),
        ),
        migrations.AddIndex(
            model_name="ticketattachment",
            index=models.Index(
                fields=["organization", "ticket"], name="helpdesk_ti_organiz_458395_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketcategory",
            index=models.Index(
                fields=["organization", "is_active"],
                name="helpdesk_ti_organiz_3b7540_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticketcategory",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["organization", "status"], name="helpdesk_su_organiz_de08e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["organization", "priority"],
                name="helpdesk_su_organiz_072118_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["organization", "assigned_to"],
                name="helpdesk_su_organiz_efd375_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["organization", "requested_by"],
                name="helpdesk_su_organiz_2cc298_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ticketcomment",
            index=models.Index(
                fields=["organization", "ticket"], name="helpdesk_ti_organiz_b47185_idx"
            ),
        ),
    ]
